title: <p align="center">Rajendra Singh Rao </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  
  <br>   
  I'm working on NLP, text analytics, Machine learning & deep learning related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
